on: [pull_request]
    
jobs:
  List-Repos:
    runs-on: ubuntu-latest
    name: Job para listar repositórios de um usuário
    steps:
    - name: List Repos
      uses: geovanams/action-list-repos@main
      with:
        user: geovanams
